<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>WinFormsSample</AssemblyName>
    <LangVersion>latest</LangVersion>
    <EnableDefaultItems>false</EnableDefaultItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\WinFormsSample\Program.cs" Link="Program.cs" />
  </ItemGroup>
</Project>
