<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>WpfSample</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableDefaultItems>false</EnableDefaultItems>
  </PropertyGroup>

  <ItemGroup>
    <ApplicationDefinition Include="..\WpfSample\App.xaml" Link="App.xaml" />
    <Page Include="..\WpfSample\MainWindow.xaml" Link="MainWindow.xaml" />
    <Compile Include="..\WpfSample\App.xaml.cs" Link="App.xaml.cs" />
    <Compile Include="..\WpfSample\MainWindow.xaml.cs" Link="MainWindow.xaml.cs" />
  </ItemGroup>
</Project>
