[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$SourceRoot,

    [Parameter(Mandatory = $true)]
    [string]$ScratchRoot
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$sourcePath = (Resolve-Path -LiteralPath $SourceRoot).ProviderPath
$projectDirectory = Join-Path $sourcePath "tests\apps\WinUI3Sample"
$projectPath = Join-Path $projectDirectory "WinUI3Sample.csproj"
$validatorPath = Join-Path $sourcePath "scripts\validate-winui3-test-fixture.ps1"
$legacyObjRoot = Join-Path $projectDirectory "obj"
$legacyBinRoot = Join-Path $projectDirectory "bin"
$legacyObjSeed = Join-Path $legacyObjRoot "lvt-legacy-regression"
$legacyBinSeed = Join-Path $legacyBinRoot "lvt-legacy-regression"
$objRootExisted = Test-Path -LiteralPath $legacyObjRoot -PathType Container
$binRootExisted = Test-Path -LiteralPath $legacyBinRoot -PathType Container

function Remove-EmptyDirectory {
    param([string]$Path)

    if ((Test-Path -LiteralPath $Path -PathType Container) -and
        -not (Get-ChildItem -LiteralPath $Path -Force | Select-Object -First 1)) {
        Remove-Item -LiteralPath $Path -Force
    }
}

function Assert-LegacyItemsExcluded {
    param(
        [string]$Architecture,
        [string]$Platform,
        [string]$Rid,
        [string]$BuildRoot
    )

    $itemOutput = & dotnet msbuild $projectPath `
        "-p:Platform=$Platform" `
        "-p:PlatformTarget=$Platform" `
        "-p:RuntimeIdentifier=$Rid" `
        "-p:BaseOutputPath=$BuildRoot\build\" `
        "-p:OutputPath=$BuildRoot\build\" `
        "-p:BaseIntermediateOutputPath=$BuildRoot\obj\" `
        "-p:IntermediateOutputPath=$BuildRoot\obj\" `
        "-p:MSBuildProjectExtensionsPath=$BuildRoot\obj\" `
        "-getItem:Compile,None,Page" `
        -nologo 2>&1 | Out-String
    if ($LASTEXITCODE -ne 0) {
        throw "MSBuild item evaluation failed for $Architecture`n$itemOutput"
    }

    $jsonStart = $itemOutput.IndexOf("{")
    if ($jsonStart -lt 0) {
        throw "MSBuild item evaluation did not return JSON for $Architecture`n$itemOutput"
    }
    $items = $itemOutput.Substring($jsonStart) | ConvertFrom-Json
    foreach ($itemType in @("Compile", "None", "Page")) {
        foreach ($item in $items.Items.$itemType) {
            if ($item.FullPath.StartsWith(
                    $legacyObjRoot,
                    [System.StringComparison]::OrdinalIgnoreCase) -or
                $item.FullPath.StartsWith(
                    $legacyBinRoot,
                    [System.StringComparison]::OrdinalIgnoreCase)) {
                throw "$Architecture $itemType glob consumed legacy item '$($item.FullPath)'."
            }
        }
    }
}

Remove-Item -LiteralPath $legacyObjSeed -Recurse -Force -ErrorAction Ignore
Remove-Item -LiteralPath $legacyBinSeed -Recurse -Force -ErrorAction Ignore
New-Item -ItemType Directory -Path $legacyObjSeed, $legacyBinSeed -Force | Out-Null

$generatedSource = @"
// <auto-generated/>
#error A stale project-local WinUI generated source was compiled.
"@
Set-Content -LiteralPath (Join-Path $legacyObjSeed "Program.g.i.cs") `
    -Value $generatedSource -NoNewline
Set-Content -LiteralPath (Join-Path $legacyBinSeed "App.g.i.cs") `
    -Value $generatedSource -NoNewline
Set-Content -LiteralPath (Join-Path $legacyObjSeed "LegacyGenerated.xaml") `
    -Value "<Page />" -NoNewline
Set-Content -LiteralPath (Join-Path $legacyBinSeed "LegacyGenerated.xaml") `
    -Value "<Page />" -NoNewline
[System.IO.File]::WriteAllBytes(
    (Join-Path $legacyObjSeed "App.xbf"),
    [byte[]](0x6c, 0x65, 0x67, 0x61, 0x63, 0x79))
[System.IO.File]::WriteAllBytes(
    (Join-Path $legacyBinSeed "MainWindow.xbf"),
    [byte[]](0x6c, 0x65, 0x67, 0x61, 0x63, 0x79))

$seedFiles = @(
    Get-ChildItem -LiteralPath $legacyObjSeed, $legacyBinSeed -File -Recurse
)
$seedHashes = @{}
foreach ($file in $seedFiles) {
    $seedHashes[$file.FullName] = (Get-FileHash -LiteralPath $file.FullName).Hash
}

try {
    foreach ($configuration in @(
        @{ Architecture = "x64"; Platform = "x64"; Rid = "win-x64" },
        @{ Architecture = "x86"; Platform = "x86"; Rid = "win-x86" }
    )) {
        $architecture = $configuration.Architecture
        $buildRoot = Join-Path $ScratchRoot $architecture
        Remove-Item -LiteralPath $buildRoot -Recurse -Force -ErrorAction Ignore
        New-Item -ItemType Directory -Path $buildRoot -Force | Out-Null

        Assert-LegacyItemsExcluded `
            -Architecture $architecture `
            -Platform $configuration.Platform `
            -Rid $configuration.Rid `
            -BuildRoot $buildRoot

        $publishOutput = & dotnet publish $projectPath `
            -c Release `
            "-p:Platform=$($configuration.Platform)" `
            "-p:PlatformTarget=$($configuration.Platform)" `
            -r $configuration.Rid `
            --self-contained true `
            -o "$buildRoot\bin" `
            "-p:BaseOutputPath=$buildRoot\build\" `
            "-p:OutputPath=$buildRoot\build\" `
            "-p:BaseIntermediateOutputPath=$buildRoot\obj\" `
            "-p:IntermediateOutputPath=$buildRoot\obj\" `
            "-p:MSBuildProjectExtensionsPath=$buildRoot\obj\" `
            --nologo 2>&1 | Out-String
        if ($LASTEXITCODE -ne 0) {
            throw "Architecture-isolated $architecture publish failed.`n$publishOutput"
        }

        Copy-Item -LiteralPath "$buildRoot\obj\App.xbf" `
            -Destination "$buildRoot\bin\App.xbf" -Force
        Copy-Item -LiteralPath "$buildRoot\obj\MainWindow.xbf" `
            -Destination "$buildRoot\bin\MainWindow.xbf" -Force
        & $validatorPath `
            -Root "$buildRoot\bin" `
            -IntermediateRoot "$buildRoot\obj" `
            -Architecture $architecture

        foreach ($file in $seedFiles) {
            if (-not (Test-Path -LiteralPath $file.FullName -PathType Leaf)) {
                throw "The $architecture publish deleted legacy artifact '$($file.FullName)'."
            }
            if ((Get-FileHash -LiteralPath $file.FullName).Hash -ne
                $seedHashes[$file.FullName]) {
                throw "The $architecture publish modified legacy artifact '$($file.FullName)'."
            }
        }
    }

    Write-Host "Legacy project-local bin/obj artifacts were ignored by isolated x64 and x86 publishes."
}
finally {
    Remove-Item -LiteralPath $legacyObjSeed -Recurse -Force -ErrorAction Ignore
    Remove-Item -LiteralPath $legacyBinSeed -Recurse -Force -ErrorAction Ignore
    if (-not $objRootExisted) {
        Remove-EmptyDirectory $legacyObjRoot
    }
    if (-not $binRootExisted) {
        Remove-EmptyDirectory $legacyBinRoot
    }
}
